README.md
earthmover/earthmover.py
earthmover/error_handler.py
earthmover/node.py
earthmover/nodes/operation.py
earthmover/nodes/transformation.py
earthmover/operations/column.py
earthmover/tests/earthmover.yaml
earthmover/util.py
earthmover/yaml_parser.py
example_projects/01_simple/big_earthmover.yaml
example_projects/01_simple/earthmover.yaml
example_projects/02_join/earthmover.yaml
example_projects/06_subtemplates/earthmover.yaml
example_projects/07_filetypes/earthmover.yaml
example_projects/08_html/earthmover.yaml
example_projects/10_jinja/earthmover.yaml
example_projects/10_jinja/inputs/actions.csv
example_projects/10_jinja/inputs/incidents.csv
example_projects/10_jinja/templates/behaviorDescriptor.jsont
example_projects/10_jinja/templates/disciplineAction.jsont
example_projects/10_jinja/templates/disciplineDescriptor.jsont
example_projects/10_jinja/templates/disciplineIncident.jsont
example_projects/10_jinja/templates/locationDescriptor.jsont
example_projects/10_jinja/templates/studentDisciplineIncidentAssociation.jsont
example_projects/10_jinja/templates/weaponDescriptor.jsont
example_projects/10_jinja/xwalks/behaviors.csv
example_projects/10_jinja/xwalks/disciplines.csv
example_projects/10_jinja/xwalks/locations.csv
example_projects/10_jinja/xwalks/weapons.csv

This PR introduces a fairly large change to earthmover, allowing Jinja in the yaml configuration. This means the yaml may now contain two types of Jinja: (1) run-time Jinja, such as
```yaml
transformations:
source1:
operations:
- operation: add_columns
source: $sources.source1
columns:
area_code: "{%raw%}{{phone_number[0:3]}}{%endraw%}"
```
and (**NEW**) parse-time jinja such as
```yaml
sources:
{% for i in range(1,10) %}
source{{i}}:
file: ./inputs/source{{i}}.csv
header_rows: 1
{% endfor%}
destinations:
{% for i in range(1,10) %}
destination{{i}}:
source: $sources.source{{i}}
template: ./templates/destination.jsont
extension: jsonl
linearize: true
{% endfor%}
```
Previously, only run-time Jinja (1) was available in earthmover. The addition of parse-time Jinja (2) is a **breaking …

implementing ability to use Jinja inside config YAML

---

earthmover/__main__.py
earthmover/earthmover.py
earthmover/nodes/destination.py
earthmover/operations/column.py
earthmover/runs_file.py
example_projects/10_jinja/earthmover.yaml
example_projects/run_all.sh

This PR fixes several bugs that have come up:
* `config.state_file` was being ignored when specified (thanks Mike and Eshara for pointing this out!)
* more issues with multi-line `config.macros` - the resolution here (hopefully the last one!) is to pre-load macros (so they can be injected into run-time Jinja contexts) and then just allow the Jinja to render and macro definitions down to nothing in the config YAML... you do have to be careful with Jinja linebreak supression, i.e.
```yaml
config:
macros: > # this is a macro!
{%- macro test() -%}
testing!
{%- endmacro -%}
sources:
...
```
could render down to
```yaml
config:
macros: > # this is a macro!sources:
...
```
which will fail with an error about no `sources` defined.
* charset issues when reading / writing non-UTF8 files (thanks …

several bugfixes

---

earthmover/runs_file.py
example_projects/01_simple/earthmover.yaml

Fixing a bug Jules found, where earthmover would attempt to hash missing optional sources, causing an error.

skip hashing missing optional source files

---

README.md
earthmover/earthmover.py

When Dask must spill data to disk, it writes files (Parquet, I believe) to a temporary location. This is configurable to Dask via [the `temporary_directory` option](https://github.com/dask/dask/pull/4774), but earthmover was not exposing it.
This update adds an earthmover config `tmp_dir` where you can specify the path Dask should use.

adding ability to configure the dask tmp_dir

---

earthmover/earthmover.py
example_projects/run_all.sh

This PR fixes a bug where if the path to the specified results_file does not exist, earthmover would fail instead of just creating it.
I'm also sneaking in a minor tweak to the test suite to suppress earthmover warnings about being invoked without a specific command.

create results_file path if it does not already exist

---

earthmover/earthmover.py
earthmover/node.py
earthmover/nodes/destination.py
earthmover/nodes/operation.py
earthmover/nodes/source.py
earthmover/nodes/transformation.py
earthmover/operations/dataframe.py
earthmover/operations/row.py

This branch incorporates several fixes and improvements to the RC/1.0.0 Yaml Refactor branch:
- Add `show_progress` and `chunksize` as optional state and node configs.
- Update `Destination.data` to reflect the object being written, not the input DataFrame.
- Implement Tom's performance-improvements to `FileDestination`, `JoinOperation`, and `DistinctRowsOperation`.
- Force a `NotImplementedError` when `Operation.post_execute()` is called (as data cannot be persisted at the Operation-level.

Rc/1.0.0  yaml version 2  dask performance improvements

---

earthmover/runs_file.py

Fixing a small bug where earthmover would check for a 'file' for remote sources which do not have files, causing an error.

switch logic order for checking if source is remote

---

CHANGELOG.md
earthmover/earthmover.py
earthmover/runs_file.py

This PR updates hashing logic to skip when a Source file is a directory (i.e., Parquet). See this [Monday ticket](https://educationanalytics.monday.com/boards/6058716254/pulses/6103720040).
Should we consider an approach where Parquet directories are actually hashed? How can this be done efficiently?

Remove hashing on file source directories

---

CHANGELOG.md
README.md
earthmover/tests/expected/species_count_by_zoo.jsonl
earthmover/tests/sources/zoos.csv
example_projects/07_filetypes/earthmover.yaml

This PR fixes typographical errors in earthmover's documentation and comments. It's based on [this PR](https://github.com/edanalytics/earthmover/pull/58) which we've decided to close without including the tooling/configuration in that PR into earthmover.

fixing typos in docs and comments

---

earthmover/util.py

When source data is _nested_ JSON, earthmover makes a column per _top level_ key, with values as strings... which may themselves be JSON. This PR adds a `fromjson()` function which can be called from within Jinja templates to parse such JSON strings into actual objects which can be traversed or used. (Name choice of `fromjson` is [based on dbt](https://docs.getdbt.com/reference/dbt-jinja-functions/fromjson).)
In the future, we could consider providing a more extensible way for users to specify their own functions to be injected into Jinja, but this small addition unblocks some development of the [LIF translator](https://github.com/BMGF-LIF/lif-translator/) for now.

adding fromjson() function to Jinja

---

earthmover/earthmover.py
earthmover/node.py
earthmover/nodes/operation.py
earthmover/yaml_parser.py

This PR makes the following changes to the `feature/project_composition` branch:
- Add `__file__` as a YamlMapping attribute based on the template file it is parsed from
- Move dict-merging logic into YamlMapping as `YamlMapping.update()`
- Update file and line metadata during merges
- Move dict-write logic into YamlMapping as `YamlMapping.to_disk()`
- Minor bugfix to operation name referencing in error output

Feature/project composition  refactor yaml mapping

---

CHANGELOG.md
earthmover/__main__.py
earthmover/earthmover.py
earthmover/error_handler.py
earthmover/nodes/destination.py
earthmover/nodes/node.py
earthmover/nodes/source.py
earthmover/nodes/transformation.py
earthmover/operations/column.py
earthmover/operations/dataframe.py
earthmover/operations/groupby.py
earthmover/operations/row.py

Changes from RC/0.3.0
- Add comments and clean up __main__.py
- Add `Node.full_name` and `Node.set_upstream_source()`
- Add `Earthmover.load_project_configs()` that automatically updates `Earthmover.params` and `Earthmover.macros` during configs processing (DRY)
- Make `user_configs`, `project_graph`, and `graph` lazy objects that are initialized during `Earthmover.compile()` or `Earthmover.deps()`
- Move "earthmover_composed.yaml" write to `Earthmover.compile()`
- Unify `Earthmover.compile()` with `Earthmover.build_graph()`
- Refactor `Earthmover.compile_node_configs()` to its own helper class
- Simplify initialization of `Earthmover.{sources, transformations, destinations}` using `Earthmover.compile_node_configs()`
- Update `Earthmover.merge_packages()` to optionally return refactored …

Rc/0.3.0  refactor build graph

---

README.md
earthmover/earthmover.py
earthmover/package.py
requirements.txt

This PR fixes an issue with `earthmover deps` hanging indefinitely as it attempts to clone a private repo and waits for a user without stored credentials to enter a username and password. The git clone command will timeout after the time specified by the optional `git_auth_timeout` config. Default is 60 seconds, long enough to still allow a human user to enter a username and password during local development.
In making this change I was able to remove the GitPython dependency, as the `git clone` command is now handled by `subprocess`.
I tested this locally to ensure unchanged behavior when credentials are stored and I ran it in a docker container without git credentials to test the timeout.

Git clone timeout when running `earthmover deps`

---

earthmover/nodes/destination.py

This PR fixes a bug introduced in earthmover 0.2.0. Writing out destination files [was done](https://github.com/edanalytics/earthmover/blob/6094c1ba0e21253c85a9a7c15913764acf7bc14e/earthmover/nodes/destination.py#L107-L111) with `Dask.to_csv()` and some "invisible" escape characters, however when a destination declared `linearize: False` (which prevents stripping out newline characters from each rendered Jinja template) these "invisible" characters were present in the output file.
Now, like we `render_row()` to render a Jinja template for each row of a dataframe, we similarly `write_row()` to append the rendered row to an open file handle.
I tested performance by loading a 31MB, 1M-row, 3-column CSV file and immediately writing it to a destination with the following template: …

Fix escape chars in output when `linearize: False`

---

earthmover/nodes/source.py

This simple PR fixes a bug [introduced](https://github.com/edanalytics/earthmover/blob/rc/0.3.2/earthmover/nodes/destination.py#L121) in earthmover 0.3.0 where nested JSON would be loaded as a stringified Python dictionary, which is difficult to use in downstream Jinja.
Example: a JSONL file like
```jsonl
{"key1":"value1", "key2":{"key2a":"value2a", "key2b":"value2b"}}
{"key1":"value3", "key2":{"key2a":"value4a", "key2b":"value4b"}}
```
would result in a dataframe like
| key1 | key2 |
| --- | --- |
| "value1" | "{'key2a': 'value2a', 'key2b': 'value2b'}" |
| "value1" | "{'key2a': 'value2a', 'key2b': 'value2b'}" |
(key2 is a string representation of a Python dictionary) instead of
| key1 | key2 |
| --- | --- |
| "value1" | {'key2a': 'value2a', 'key2b': 'value2b'} |
| "value1" | {'key2a': …

Fix read_json with nested JSON

---

README.md
earthmover/__main__.py
earthmover/earthmover.py

Adds an argument to `earthmover.compile()` to specify whether a `earthmover_compiled.yaml` will be written to disk. Defaults to false, set to true for `earthmover compile` commands.

Only write `earthmover_compiled.yaml` on compile, not run

---

earthmover/util.py

The [earthmover documentation](https://github.com/edanalytics/earthmover/#transformations) states that you can use `{{__row_data__['col_name']}}` in the Jinja expressions of an `add_columns` or `modify_columns` operation, but that's currently not true - that variable is only available in the context when rendering a Jinja template of a destination. This PR fixes this bug.
Separately, the documentation also states that you can use `{{__row_number__}}` in your Jinja expressions, but that's not actually implemented anywhere in earthmover, and implementing it is non-trivial given the Dask backend. Perhaps in the short-term this should be removed from the documentation while we figure out the best way to implement it.

Fix `__row_data__` in `add_columns` and `modify_columns` operations

---

README.md
earthmover/operations/dataframe.py
earthmover/operations/operation.py

Per discussion with Jay following PR #89, we decided to split out the debug operation to a separate PR for now - this is it.
We will return to discussion of the `earthmover show` command and how to best to implement it in the future.

adding the `debug` operation

---

earthmover/operations/dataframe.py

This PR resolves a bug in Earthmover where if a dataframe with multiple identically-named columns is passed into the union operation, the following stacktrace appears:
```
Traceback (most recent call last):
File "/home/jalvord/.venv/earthbeam__sc_test/src/earthmover/earthmover/operations/dataframe.py", line 175, in execute
data = dd.concat([data, source_data], ignore_index=True)
File "/home/jalvord/.venv/earthbeam__sc_test/lib/python3.8/site-packages/dask/dataframe/multi.py", line 1327, in concat
return stack_partitions(
File "/home/jalvord/.venv/earthbeam__sc_test/lib/python3.8/site-packages/dask/dataframe/multi.py", line 1102, in stack_partitions
needs_astype = [
File "/home/jalvord/.venv/earthbeam__sc_test/lib/python3.8/site-packages/dask/dataframe/multi.py", line 1105, in <listcomp> …
```

Bugfix: union fails with duplicate columns

---

README.md
earthmover/operations/operation.py
earthmover/operations/row.py
earthmover/tests/earthmover.yaml

This PR implements a `limit_rows` operation. For example:
```yaml
- operation: limit_rows
count: 5 # required, no default
offset: 10 # optional, default 0
```

implementing a limit_rows operation

---

README.md
earthmover/nodes/destination.py
earthmover/nodes/node.py
earthmover/nodes/source.py
earthmover/nodes/transformation.py

Any node (source, transformation, destination) can now declare `require_rows: True` or `require_rows: 10` to provide a way to ensure zero-row nodes stop earthmover execution.

add support for a `require_rows` boolean or non-negative int on any node

---

README.md
earthmover/nodes/destination.py

This PR adds support for a destination node's `header` and `footer` to contain Jinja. The first row of data is passed in, so `__row_data__.pop('__row_data__').keys()` contains the column names, which can be used to define a dynamic header/footer. For example:
```yaml
destinations:
input_no_student_id_match:
source: $transformations.input_no_student_id_match
template: ./verbatim.csvt
header: |
{%raw%}{% for k in __row_data__.pop('__row_data__').keys() %}{{k}}{% if not loop.last %},{% endif %}{% endfor %}{%endraw%}
extension: csv
linearize: True
```

add support for Jinja in a destination node header and footer

---

earthmover/nodes/destination.py

Use dataframe column to generate a pseudo row to pass to header and footer Jinja renders on destination write.
This circumvents an IndexError when writing an empty dataframe with a Jinja-rendered header or footer.

Hotfix: Refactor Jinja Destination Headers and Footers

---

earthmover/__main__.py
earthmover/earthmover.py
earthmover/yaml_parser.py

This PR adds a `--set` flag to the cli to enable overriding values in _compiled_ `earthmover.yml`. For example, you can
```bash
earthmover run -c path/to/earthmover.yml --set config.tmp_dir /tmp/earthmover
```
or
```bash
earthmover run -c path/to/earthmover.yml --set destinations.schools.extension ndjson
```
or even
```bash
earthmover run -c path/to/earthmover.yml --set sources.schools.file ./myschools.csv
```
Spaces in values are possible by enclosing the value in quotes, such as
```bash
earthmover run -c path/to/earthmover.yml --set sources.schools.file './my schools with spaces.csv'
```
Only values of "simple" types (bool, int, float, str) can be overridden... if you try something like
```bash
earthmover run -c path/to/earthmover.yml --set sources.schools.columns …
```

adds a `--set` flag to the cli to enable overriding values in _compiled_ `earthmover.yml`

---

earthmover/nodes/source.py
example_projects/07_filetypes/earthmover.yaml

This change replaces column alias logic with column select logic in defined sources.
@tomreitz This does not work for Example Project 07_filetypes on ORC files. We may want to make column renaming the optional behavior instead of the default.

Refactor Source columns list logic as a select instead of a rename.

---

CHANGELOG.md
earthmover/earthmover.py
earthmover/nodes/source.py
earthmover/package.py

Given the following setup:
- `pkg_A` depends on `pkg_B` (doesn't matter how)
- `pkg_B` has `pkg_C` as a **local** dependency
- You run `earthmover deps` on `pkg_A`
This fails because Earthmover looks for the path to `pkg_C` relative to `pkg_A/earthmover.yaml` instead of `pkg_B/earthmover.yaml`, and can't find it.
Bug spelled out [here](https://edanalytics.slite.com/app/docs/2ici_xnKjKVy-s#f8925219) -- fix was removing the `.strip('./')` from the `load_package_yaml` function
Currently we require `--results-file ./results.json` and forbid `--results-file results.json`. The latter should be allowed too
Tested the fixes locally but couldn't hurt for others to try it out as well.

Bugfix: Project composition – nested local packages & resolving relative paths

---

CHANGELOG.md
earthmover/earthmover.py

Fixes a bug introduced in #130 - thanks to @jayckaiser for reporting

Fix `earthmover deps` fails when not all params are passed

---

CHANGELOG.md
earthmover/__init__.py

#136 was insufficient to guarantee backwards compatibility with Python versions < 3.10. Here we move the entire set of configuration instructions into that conditional

Make all pandas/dask config conditional on >3.10

---

earthmover/nodes/source.py

rework optional fields creation to avoid recursive dataframe updates
I found that the recursion errors we were seeing in CIRCLE bundle likely traced back to this line
`self.data[field] = ""`
(something about dask doing checks under the hood each time a dataframe update happens)
I also wanted to resolve the repeated warnings we were receiving both before and after resolving the recursion:
```
PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling frame.insert many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use newframe = frame.copy()
```
Those warnings are now gone, I believe because of the change to construct the new columns separately & then reindex

fix optional fields recursion

---

CHANGELOG.md
earthmover/operations/column.py

Add the set difference of the columns to the error messages so the user knows what is missing

fix: error messages for `keep_columns` and `drop_columns` do not specify the columns
